### ISSUE TITLE
[하부 섹션] 키 이미지 및 메세지 변경 요청

### ISSUE THREAD

**Issue by hello-catsai** [oyoriasia/brand-home#10]
우리의 서비스를 디지털로 확장합니다. 
그래도 조직의 미션인 여성, 지역, 사회적 가치 실현이라는 키워드를 지켜나갑니다. 

앱을 통해서 서비스 한다는 부분을 알고, 인지할 만한데...
가운데 손 모양 제거, 가운데 부분의 키 이미지 변형 필요(제안)

![Screen Shot 2022-07-07 at 5 13 07 PM](https://user-images.githubusercontent.com/107086647/177725251-44c293f6-fcd5-4935-82cb-988cd12e3dc5.png)

**Comment by choochu9** [comment]
수정되었습니다~ 확인 부탁드립니다.

**Comment by hello-catsai** [comment]
오늘 피드백 받아보겠습니다.

**Comment by hello-catsai** [comment]
@choochu9

키 이미지에서 주변에 있는 원들에 있는 형상은 괜찮은데
오요리아시아에서 진행하려는 디지털 사업이 손+모바일로 한계되는 것 같은 느낌이 듭니다. (그대로 적어봄)

지난번 시안은 제 선에서 잘랐는데

이쪽 키 이미지를 변경이 마지막 요청입니다.

**Comment by hello-catsai** [comment]
![Screen Shot 2022-07-14 at 1 04 36 PM](https://user-images.githubusercontent.com/107086647/178897173-6b109e60-ae20-4aa0-a75f-675f821ce63b.png)

테레노 -> 떼레노

**Comment by hello-catsai** [comment]
요 상태로 우선 정리합니다.
