### ISSUE TITLE
B corp 수상 공지 - 메인 슬라이드

### ISSUE THREAD

**Issue by hello-catsai** [oyoriasia/brand-home#12]
결국 매번 한글을 넣은 이미지를 편집하는데 한계는 있을 수 있어서 배경으로 넣고, 한글을 적을 수 있는 영역을 마련해 주시면 감사하겠습니다. 

"비콥 BEST FOR THE WORLD™ 2022 로 선정되었습니다 "

이미지 리소스 : https://bcorp.imagerelay.com/flc/6c02d58499024db3b7ae8cc42649178d/1614928

가이드 pdf를 확인하세요.

![Image](https://user-images.githubusercontent.com/107086647/179928764-324d41b8-f388-467a-a29d-a14a25522070.png)

**Comment by hello-catsai** [comment]
[BFTW-2022---Toolkit-for-BFTW-Community--English-.pdf](https://github.com/oyoriasia/brand-home/files/9147820/BFTW-2022---Toolkit-for-BFTW-Community--English-.pdf)

**Comment by woonjjang** [comment]
고생하셨습니다. 공지 및 링크 완료
