### ISSUE TITLE
QA 및 내부 피드백  & 교체 (수정)

### ISSUE THREAD

**Issue by hello-catsai** [oyoriasia/brand-home#5]
관련되어 페이지 수정

-->> 경영팀으로 인수인계 후 / 수정요청 있을 때 외주 작업자 요청하는 프로세스 정리
-->> 금,토,일,월

**Comment by hello-catsai** [comment]
목요일 오후 3시 내부 공유, 피드백( 아임웹에 올라간 형태로 시안 공유)

**Comment by hello-catsai** [comment]
추가 요소
- 헤더 / 남색 IT기업이 되어도 섹션에 B corp 인증마크와 링크를 넣으면 어떨까요 ? (한운장) 
- 비콥과 1%panet -네 동의합니다 -이지혜
- 메인 피처룩 추가 - 한운장
- 상인들이 죽어간다는 부분 너무 강해서 문구 변경 / 사진교체도 고려 (Covid 느낌으로)

변경
-브랜드에는 뗴레노와 엘초코데뗴레노가 들어가고
협력사는 뗴레노는 아닌것 같아요.
오히려 협력사→파트너로 해서: nepal cafe mitini를 넣는게 맞는 것 같습니다.


블로그
- 블로그는 네이버 블로그 같은 형식인가요? 아니며 게시판 형식인가요? 썸네일이 보이는 게시판, 카테고리 필터가 어울리는 디자인 필요

**Comment by choochu9** [comment]
수정사항 확인했습니다~ 오늘까지 반영하도록 하겠습니다.
키비주얼은 어떤 내용으로 들어가면 좋을까요?

**Comment by choochu9** [comment]
[블로그 디자인 종류]
<img width="991" alt="스크린샷 2022-06-29 오전 11 44 52" src="https://user-images.githubusercontent.com/107188129/176341457-04a2e0ab-21f6-44d4-afe7-e8bd133a4402.png">

**Comment by hello-catsai** [comment]
https://brand.oyori.asia 모바일 푸터를 현재 웹 및 링크랑 동일하게 맞춰주세요.

**Comment by hello-catsai** [comment]
취약계층 역량강화 섹션 @choochu9 

몇가지 팩트만 먼저 보내드리고
내일 다시 피드백 하겠습니다

1. 3년연속 미쉐린 원스타 선정
미쉐린가이드 서울 [2020-2022](tel:20202022) 
미쉐린 가이드 서울 2021, 2022 (추가)더불레이드~~> 더불레이드 삭제 

2. 아시아 빈곤 여성__> 아시아 여성

**Comment by hello-catsai** [comment]
2개 박스로 되어 있는 영역에서 회사 생활은 삭제 -> 투자 부분만 남아 있도록 영역 내용 교체 @choochu9

**Comment by hello-catsai** [comment]
1. 단어 통일
테레노 --> 떼레노(스페인어로)

2. 발자취
2013년과 2014년이 연혁이 동일합니다
확인다시 한번 해주세요

2014.
스패니시 다이닝 북촌 Terreno 레스토랑 오픈

2019
B corp 인증, 2019년 Best of all, Community 부문 Global 상위 10% 선정

2020
(기존 내용 삭제 해주세요)
서울시 청청지역 프로젝트 도시청년 지역 일자리 매칭 강원&제주 사무국 운영


2021
강원 외식업 소셜벤쳐 인큐베이팅 사업 운영 (강원창조경제센터, 소풍벤쳐스, 오요리아시아 컨소시움)
B corp 2021년 Community 부문 Global 상위 5% 선정
네팔 여성 다와 (Dawa) Cafe Mitini 3호점 창업 지원

@woonjjang  확인
